FROM harbor.aigauss.com/base-images/tor15:0.6.0_cu101 

RUN apt-get -y update && \
	apt-get -y install build-essential
 
RUN pip3 install gunicorn 

COPY requirements.txt .
RUN pip3 install -r requirements.txt


WORKDIR /app/nmt_trans
COPY nmt_trans .
ADD data /app/data

ENV PYTHONPATH="${PYTHONPATH}:/app" \
    DICT_HOST=rm-uf6it2u39agqevqh8.mysql.rds.aliyuncs.com \
    DICT_PORT=3306 \
    DICT_UNAME=spider \
    DICT_PWD=spider_bot \
    DICT_DB=tgy_spider \
    DICT_TABLE=word_dict \
    DICT_TYPE=""	
	

CMD gunicorn  -w 2 -b 0.0.0.0:8864 -t 3000 'web.www:load_app("conf/chat_config.json")'

EXPOSE 8864 
