# For followme en2zh release

FROM harbor.aigauss.com/base-images/tor15:0.6.0_cu101 

RUN apt-get -y update && \
	apt-get -y install build-essential
 
RUN pip3 install gunicorn 

COPY requirements.txt .
RUN pip3 install -r requirements.txt


WORKDIR /app/nmt_trans
COPY nmt_trans .
ADD data /app/data

ENV PYTHONPATH="${PYTHONPATH}:/app" \
	DICT_HOST=alibeta-mysql.followme-internal.com\
    DICT_PORT=3326\
    DICT_UNAME=fmbetadb002\
    DICT_PWD=31Bawd0c5GEq\
    DICT_DB=news_tag\
    DICT_TABLE=word_dict\
    DICT_TYPE=""	
	

CMD gunicorn  -w 2 -b 0.0.0.0:8864 -t 3000 'web.www:load_app("conf/chat_config.json", None)'

EXPOSE 8864 
